#!/bin/bash

#BAT="3"
BAT=$(acpi -b)
PERCENTAGE=$(acpi -b | awk '{print $4 }')
STAT=$(acpi -b | awk '{print $3}')
#STAT="Full,"
REM=$(acpi -b | grep -E -o "[0-9][0-9]:[0-9][0-9]:[0-9][0-9]")

if [[ $STAT == "Discharging," ]]; then
    ICON="♦"
elif [[ $STAT == "Charging," ]]; then
    ICON="♠"
elif [[ $STAT == "Full," ]]; then
    ICON="✓"
else
    ICON="?"
fi

#if [[ ${PERCENTAGE::-2} -le 20 && ${PERCENTAGE::-2} -ge 6 && $STAT=="Discharging," ]]; then
#    notify-send -u critical -t 10000 -c Battery "Low Battery" "Charge your Battery!"
#    ICON="❗"
if [[ ${PERCENTAGE::-2} -le 10  &&  $STAT == "Discharging," ]]; then
    ICON="!!"
    notify-send -u critical -t 2000 -c Battery "Low Battery!" "Charge your Battery!"
#elif
#    [[ ${PERCENTAGE::-2} -ge 95 && $STAT == "Charging," ]]; then
#    zenity --notification --text="Full Battery!"
fi

echo -e "$ICON $PERCENTAGE $REM"
#echo "$STAT"
